### ISSUE TITLE
3.0 Members Issue

### ISSUE THREAD

**Issue by ModGallus** [Mige5/rs2006sp#32]
Members content is perma locked regardless of server configs.

No matter the setting, you will always be considered a F2P Account

**Comment by Mige5** [comment]
I just tested, it should be working?

**Comment by ModGallus** [comment]
I added a video to the #Media section of the Discord.

Note: I also tested with other settings in the configs and that doesn't fix it either.
Note: I also transferred my character files from 2.5 to 3.0 so I could keep my progress. Not sure if that caused it. I will test an account right now.
